### ISSUE TITLE
ACE2 TODO List

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACE.jl#23]
Please add further items in a separate post

- [x] Merge the different coupling coefficient structures
- [x] merge the different coupling coefficient implementations
- [x] gradients (@cortner)
- [x] Spherical tensors (@zhanglw0521)
- [x] Euclidean tensors (@MatthiasSachs)
- [x] multiple `n, l, m`
- [ ] multiplying and concatenating properties

**Comment by cortner** [comment]
@zhanglw0521 I think you could now start working on the spherical tensors while in parallel discussing with Matthias how to unify our three codes.

**Comment by cortner** [comment]
one final item missing, but I will ignore this. This would just be a convenience layer that we can add at some later date. The main features of ACE2 are ready.
