### ISSUE TITLE
Roadmap for 1.x and 2.x

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACE.jl#8]
This issue is to summarise the next steps in the ACE + IPFitting game, comments and discussion are very welcome. This roadmap will be adjusted according to discussions.

## ACE 1.x

Overall Goal: rock-solid and usable linear regression, some basic hyper parameter optimisation

### High Priority: 
- [x] fix slow basis assembly since v0.6 (cf. #10 for further work)
- [x] fix crashing multi-threaded code in `IPFitting`
- [x] shift to DAG evaluation code as default  (cf v0.7.0)
- [x] general repulsive core (cf v0.7.0)
- [x] tests for cross-version compatibility and performance regression (will enforce compatibility only from v1.0.0 onwards) (cf. v0.7.1)
- [x] #52
- [ ] general cleanup and revamp of `IPFitting` (@casv2)

### Next steps, could be 1.x or beyond
- [x] Create a "wrapper" module that gives a nicer user-interface that will ideally remain independent of developments on the ACE backend (to discuss with Cas)
- [ ] Generate basis for fixed cost rather than for fixed degree; cf. #2 
- [ ] general sure-fire way to generate repulsive cores (Gabor, Cas, CO to discuss)
- [ ] real basis (CO); this should give an extra factor 2
- [ ] optimisation of distance transform (Andres)
- [ ] optimisation of radial basis (Andres)
- [ ] Sparsification of basis (IPFitting, sparse priors, Matthias, ...)
- [ ] automated weight selection through iteratively reweighed least squares (IPFitting)
- [ ] Orthogonal basis (= pure basis; to be discussed with Simon)
- [ ] Revisit regularisation with different metrics 
- [ ] kernel and GP type regression using ACE basis as feature vectors
- [ ] Incorporate aPIPs via code-generated DAG evaluation

## ACE 2.x

ACE 2.x will focus on improved composability and nonlinear models

- [x] arbitrary densities
- [x] bond model (cylindrical symmetry) (CO, best to move to 2.x)
- [x] neighbour counting models
- [x] rewrite multi-species via discrete density
- [x] nonlinear combination (e.g. Finnis Sinclair) - this could be shifted to 1.x
- [ ] multi-scale basis, medium-range interaction
- [ ] composition via general densities
- [ ] self-consistency and Coulomb

cc @gabor1 @casv2 @andresrossb

**Comment by cortner** [comment]
maybe it is actually time to tag ACE 1.0, go to full maintenance mode there and tag the latest development branch with something else.

**Comment by cortner** [comment]
this is so old now, can close it and start a new list if we want to.
